Add support for usual reporters feature
haecker-felix/hebbot pull request #25
Opened 2021-09-27 15:53 UTC by thibaultamartin

Closes #23

2021-09-27 17:41 UTC, haecker-felix requested changes
We should special case that the bot ignores his own reaction events for the case someone adds the bot itself as editor.

2021-09-27 17:41 UTC, haecker-felix commented on src/bot.rs
> +    async fn send_reaction(&self, reaction: &str, event_id: &EventId) {
Should rename `event_id` to something more obvious like `msg_event_id`

2021-09-27 17:41 UTC, haecker-felix commented on src/bot.rs
> +        //println!("I should add the {} emoji eventually!", reaction);
That should be removed ;)

2021-09-27 17:41 UTC, haecker-felix commented on src/bot.rs
> +        //let event_id = event_id.to_string();
why?

2021-09-27 18:14 UTC, thibaultamartin commented on src/bot.rs
> +    async fn send_reaction(&self, reaction: &str, event_id: &EventId) {
Fixed in eacffc6

2021-09-27 18:14 UTC, thibaultamartin commented on src/bot.rs
> +        //println!("I should add the {} emoji eventually!", reaction);
Fixed in eacffc6

2021-09-27 18:18 UTC, thibaultamartin commented on src/bot.rs
> +        //let event_id = event_id.to_string();
I need the event ID (the EventID struct) a few lines below. This overrode the parameter and I couldn't retrieve it :)

2021-09-28 08:41 UTC, thibaultamartin commented
> We should special case that the bot ignores his own reaction events for the case someone adds the bot itself as editor.

Fixed in 5b395c3

2021-10-03 13:46 UTC, haecker-felix requested changes

2021-10-03 13:46 UTC, haecker-felix commented on configuration/config.toml.example
> +editors = [
Is it `usual_reporters` or `editors`?

2021-10-03 13:46 UTC, haecker-felix commented on configuration/config.toml.example
> +editors = [] # Mandatory for empty projects
No need to add mandatory info, every config field is mandatory.

2021-10-03 13:46 UTC, haecker-felix commented on src/bot.rs
> -        let event_id = event_id.to_string();
Keep this, then you don't need to convert it in line 309.

2021-10-03 13:49 UTC, haecker-felix commented
I wonder if we should do the same thing for sections as well. For example in TWIG we have a reporter who often reports stuff for a section (eg. GNOME Circle section). So it would be neat if hebbot automatically suggests section emojis too.

2021-10-03 17:13 UTC, thibaultamartin commented on configuration/config.toml.example
> +editors = [
Fxied in 358e8fe4f998d4460201044ed7315e70e7404e61

2021-10-03 17:13 UTC, thibaultamartin commented on configuration/config.toml.example
> +editors = [] # Mandatory for empty projects
Fixed in 358e8fe4f998d4460201044ed7315e70e7404e61

2021-10-03 17:16 UTC, thibaultamartin commented
> I wonder if we should do the same thing for sections as well. For example in TWIG we have a reporter who often reports stuff for a section (eg. GNOME Circle section). So it would be neat if hebbot automatically suggests section emojis too.

I added support for sections as well

2021-10-03 18:15 UTC, merged