Fixes #50 - make verbs configurable
haecker-felix/hebbot pull request #51
Opened 2021-11-16 10:58 UTC by GregSutcliffe

My first attempt at Rust, so comments very welcome :)

Also, for some reason, using "./config.toml" wasn't working in gitignore while I was testing, so I changed it to ignore those files in the project root. can drop that commit if it's a problem, just let me know.

2021-11-26 21:10 UTC, haecker-felix requested changes
Looks good, I can merge it if you fix my two nitpicks :)

2021-11-26 21:10 UTC, haecker-felix commented on .gitignore
> +/template.md
Nitpicking: Please don't remove the already added config lines, I need them for my setup. Just add your files additionally.

2021-11-26 21:10 UTC, haecker-felix commented on doc/example_config/config.toml
> +verbs = ["reports", "says", "announces"]
Nitpick II: Please move the `verbs` line between `video_markdown` and `update_config_command`, I would like to keep the config file a bit sorted (also in `config.rs`)

2021-11-29 10:14 UTC, GregSutcliffe commented on .gitignore
> +/template.md
Sure, no worries. I wouldn't normally touch such things, but it appeared to not be working at all on my machine - template.md was still showing up for commit, so I assumed I was fixing a typo rather than making a material change.

2021-11-29 10:50 UTC, GregSutcliffe commented on doc/example_config/config.toml
> +verbs = ["reports", "says", "announces"]
+1 for sorting, should have spotted that.

2021-11-29 10:57 UTC, GregSutcliffe commented
Nitpicks fixed, thanks for the review!

2021-12-09 18:45 UTC, haecker-felix requested changes

2021-12-09 18:45 UTC, haecker-felix commented on doc/example_config/config.toml
> +verbs = ["reports", "says", "announces"]
You forgot to update it here, no? :)

2021-12-09 18:45 UTC, haecker-felix commented on src/render.rs
> +fn random_verb(config: &Config) -> String {
Instead of having to reference `config` here it would be easier to move that method directly to `Config`

2021-12-13 15:38 UTC, GregSutcliffe commented on doc/example_config/config.toml
> +verbs = ["reports", "says", "announces"]
Oh lol, I edited my *actual* config. Which isn't committed, ofc. Fixed

2021-12-13 15:39 UTC, GregSutcliffe commented on src/render.rs
> +fn random_verb(config: &Config) -> String {
That's fair. I *think* I moved it correctly (at least, it still seems to work :P)

2021-12-18 21:20 UTC, merged