Fixes #40 - give projects and sections their own templates
haecker-felix/hebbot pull request #53
Opened 2021-11-16 13:53 UTC by GregSutcliffe

OK, this was a bit harder, I learned some Rust :)

I'm not sure if the reading of the template files is in the right place, but I also wasn't sure about how to pass the resulting strings around, so this seemed cleaner. Feedback *very* welcome!

2021-11-26 21:04 UTC, haecker-felix requested changes
Please don't forget the update the example `docker-compose.yml` to reflect the new env variables. 

https://github.com/haecker-felix/hebbot/blob/master/doc/example_config/docker-compose.yml

2021-11-26 21:04 UTC, haecker-felix commented on src/render.rs
> +        section_template = section_template.replace("{{section.title}}", &section.title);
Hmm... Aren't you overwriting the `section_template` value here? In the next iteration of `for (_, render_section) in render_sections` you won't have something `{{}}` to replace, since you have overwritten it (Or am I missing something?)

2021-11-26 21:04 UTC, haecker-felix commented on src/render.rs
> +            project_template = project_template.replace("{{project.title}}", &project.title);
I guess the same problem with the `project_template`

2021-11-29 11:01 UTC, GregSutcliffe commented on src/render.rs
> +    let path = match env::var("SECTION_TEMPLATE_PATH") {
That's probably fair, yes. I was still getting a feel for Rust at this point - having worked on #55 I think I can do this now. I guess this would go in `utils.rs` ?

2021-11-29 11:31 UTC, GregSutcliffe commented on src/render.rs
> +        section_template = section_template.replace("{{section.title}}", &section.title);
You are 100% correct.

I *think* I misunderstand this as being a scoped copy of section_template - but I wrongly only tested with a single section, so I didn't catch it. I just tested with 2 news items in 2 different sections & projects, and yes, it goes wrong.

I've added a local variable to take a copy of `section_template` for gsub'ing.

2021-11-29 11:31 UTC, GregSutcliffe commented on src/render.rs
> +            project_template = project_template.replace("{{project.title}}", &project.title);
As above, same fix.

2021-11-29 11:34 UTC, GregSutcliffe commented on src/render.rs
> +    let path = match env::var("SECTION_TEMPLATE_PATH") {
Oh, yes, you already said to put it in utils. Working on that now.

2021-11-29 12:09 UTC, GregSutcliffe commented
Updated. Based on the discussion in #51 I've also duplicated the lines in .gitignore, since I assume we'll see the same behaviour for these new files.

2021-11-29 12:14 UTC, GregSutcliffe commented on src/render.rs
> +            project_template = project_template.replace("{{project.title}}", &project.title);
I've also used clearer names - "project**s**_text" and "project_text" is not good naming on my part...

2021-12-09 18:53 UTC, haecker-felix requested changes

2021-12-09 18:53 UTC, haecker-felix commented on src/render.rs
> +    let mut template = utils::template_from_env("REPORT_TEMPLATE_PATH", "./report_template.md");
nitpick: Name it `report_template` so that it is unambiguous and consistent with the other variables.

2021-12-19 14:13 UTC, merged