Parse message to add reactions
haecker-felix/hebbot pull request #69
Opened 2022-09-05 09:03 UTC by thibaultamartin

Fixes #68

2022-10-05 08:14 UTC, jplatte commented on src/bot.rs
> +                if regex.is_match(&msg_lowercase) {
```suggestion
            let msg_lowercase = .to_lowercase();
            for project in &self.config.projects {
                let regex = Regex::new(&format!(
                    "(?i)\\b{}\\b|\\b{}\\b",
                    project.name,
                    project.title,
                ))
                .unwrap();
                if regex.is_match(&news.message()) {
```

2022-10-05 08:14 UTC, jplatte commented on src/bot.rs
> +                    self.send_reaction(&project.emoji, &EventId::parse(&news.event_id).unwrap())
```suggestion
                    self.send_reaction(&project.emoji, &news.event_id)
```

2022-10-05 08:14 UTC, jplatte commented on src/project.rs
> +}
If you do this, you should also have a corresponding serialization function because `Project` also derives `Serialize` (or maybe just don't do this 😅).

2022-10-06 15:11 UTC, thibaultamartin commented on src/project.rs
> +}
Hm that's true. I think having a serialisation function makes the most sense ._.

2022-10-07 09:36 UTC, thibaultamartin commented
Note this branch was rebased on top of #70 for my own convenience, which wasn't the cleanest thing to do /o\

2022-10-07 18:42 UTC, haecker-felix requested changes
Otherwise the emoji thing it looks :+1:  from my side! Thanks for the work, and @jplatte thanks for your initial review(s)!

2022-10-07 18:42 UTC, haecker-felix commented on src/bot.rs
> +                    self.send_reaction(&project.emoji, &news.event_id).await;
Is there any reason why you implement your own `serialize` / `deserialize` for `emoji`? :) 
A simple `format!("{} ?", project.emoji)` would work, no?

2022-10-14 09:26 UTC, thibaultamartin commented on src/bot.rs
> +                    self.send_reaction(&project.emoji, &news.event_id).await;
I found it handy so the `project.emoji` was consistent wherever it was used, but that's indeed not clean. Updated :)

2022-10-14 12:42 UTC, merged